using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;

public static class WeekValidationSampleGenerator
{
    private const string OutputRoot = "Assets/Data/Test/WeekValidationSamples";
    private const string AutoGenerateSessionKey = "WeekValidationSampleGenerator.AutoGenerated";

    private sealed class SharedAssets
    {
        public SO_CardInfoTypeDefinition LetterType;
        public SO_CardInfoTypeDefinition ExternalType;
        public SO_CardInfoTypeDefinition TextbookType;
        public SO_CardInfoTypeDefinition HouseTalkType;
        public SO_CardInfoTypeDefinition VisitorType;

        public SO_FlagDefinition LetterSuspectedFlag;
        public SO_FlagDefinition ExternalInterestFlag;
        public SO_FlagDefinition HiddenInfoDetectedFlag;
        public SO_FlagDefinition VisitorRememberedFlag;

        public SO_DialogueSpeakerDefinition NemoSpeaker;
        public SO_DialogueSpeakerDefinition MaidSpeaker;
        public SO_DialogueSpeakerDefinition ParentSpeaker;
        public SO_DialogueSpeakerDefinition TutorSpeaker;
    }

    private sealed class TestInteractions
    {
        public SO_CardInteractionDefinition TrustPlus1;
        public SO_CardInteractionDefinition CuriosityPlus1;
        public SO_CardInteractionDefinition AnxietyPlus1;
        public SO_CardInteractionDefinition ObediencePlus1;

        public SO_CardInteractionDefinition SetLetterSuspected;
        public SO_CardInteractionDefinition SetExternalInterest;
        public SO_CardInteractionDefinition SetHiddenInfoDetected;
        public SO_CardInteractionDefinition SetVisitorRemembered;

        public SO_CardInteractionDefinition GroupCuriosityPlus1AndExternalInterest;
        public SO_CardInteractionDefinition ConditionalIfCuriosity3ThenTrustPlus1;

        public SO_CardInteractionDefinition LogW1WeekStart;
        public SO_CardInteractionDefinition LogW1WeekEnd;
        public SO_CardInteractionDefinition LogW1Routine;
        public SO_CardInteractionDefinition LogW1Story;
        public SO_CardInteractionDefinition LogW1ChoiceA;
        public SO_CardInteractionDefinition LogW1ChoiceB;

        public SO_CardInteractionDefinition LogW2Routine;
        public SO_CardInteractionDefinition LogW2Story;
        public SO_CardInteractionDefinition LogW2Night;

        public SO_CardInteractionDefinition LogW3WeekStart;
        public SO_CardInteractionDefinition LogW3Routine;
        public SO_CardInteractionDefinition LogW3Step;
        public SO_CardInteractionDefinition LogW3Complete;
        public SO_CardInteractionDefinition LogW3Night;

        public SO_CardInteractionDefinition LogW4Step1;
        public SO_CardInteractionDefinition LogW4Step3;
        public SO_CardInteractionDefinition LogW4ChoiceA;
        public SO_CardInteractionDefinition LogW4ChoiceB;
        public SO_CardInteractionDefinition LogW4FallbackNight;

        public SO_CardInteractionDefinition LogW5Routine;
        public SO_CardInteractionDefinition LogW5Story;
        public SO_CardInteractionDefinition LogW5Night;
    }

    [MenuItem("Tools/Week/Generate 5-Week Validation Sample SO")]
    public static void GenerateFromMenu()
    {
        GenerateInternal();
        EditorUtility.DisplayDialog(
            "Week Validation Samples",
            "5주 검증용 샘플 SO를 Assets/Data/Test/WeekValidationSamples 에 생성했습니다.",
            "확인");
    }

    public static void GenerateBatch()
    {
        GenerateInternal();
        Debug.Log("[WeekValidationSampleGenerator] Generation completed.");
    }

    [InitializeOnLoadMethod]
    private static void AutoGenerateInOpenEditor()
    {
        if (Application.isBatchMode)
        {
            return;
        }

        if (SessionState.GetBool(AutoGenerateSessionKey, false))
        {
            return;
        }

        SessionState.SetBool(AutoGenerateSessionKey, true);
        EditorApplication.delayCall += () =>
        {
            try
            {
                GenerateInternal();
                Debug.Log("[WeekValidationSampleGenerator] Auto-generated validation sample assets.");
            }
            catch (Exception exception)
            {
                Debug.LogException(exception);
            }
        };
    }

    private static void GenerateInternal()
    {
        SharedAssets shared = LoadSharedAssets();

        ResetOutputRoot();
        EnsureFolder(OutputRoot);
        EnsureFolder($"{OutputRoot}/Common");
        EnsureFolder($"{OutputRoot}/Common/Interactions");
        EnsureFolder($"{OutputRoot}/Week");

        TestInteractions interactions = CreateCommonInteractions(shared);

        SO_WeekDefinition week1 = CreateWeek1(shared, interactions);
        SO_WeekDefinition week2 = CreateWeek2(shared, interactions);
        SO_WeekDefinition week3 = CreateWeek3(shared, interactions);
        SO_WeekDefinition week4 = CreateWeek4(shared, interactions);
        SO_WeekDefinition week5 = CreateWeek5(shared, interactions);

        WriteReadme(new[] { week1, week2, week3, week4, week5 });

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Selection.activeObject = week1;
    }

    private static SharedAssets LoadSharedAssets()
    {
        return new SharedAssets
        {
            LetterType = LoadRequired<SO_CardInfoTypeDefinition>("Assets/Data/Generated/CSVImport/Card/Types/card_type_letter.asset"),
            ExternalType = LoadRequired<SO_CardInfoTypeDefinition>("Assets/Data/Generated/CSVImport/Card/Types/card_type_externalinfo.asset"),
            TextbookType = LoadRequired<SO_CardInfoTypeDefinition>("Assets/Data/Generated/CSVImport/Card/Types/card_type_textbook.asset"),
            HouseTalkType = LoadRequired<SO_CardInfoTypeDefinition>("Assets/Data/Generated/CSVImport/Card/Types/card_type_houseTalk.asset"),
            VisitorType = LoadRequired<SO_CardInfoTypeDefinition>("Assets/Data/Generated/CSVImport/Card/Types/card_type_visitor.asset"),

            LetterSuspectedFlag = LoadRequired<SO_FlagDefinition>("Assets/Data/Generated/CSVImport/Runtime/Flags/letter_suspected.asset"),
            ExternalInterestFlag = LoadRequired<SO_FlagDefinition>("Assets/Data/Generated/CSVImport/Runtime/Flags/external_interest.asset"),
            HiddenInfoDetectedFlag = LoadRequired<SO_FlagDefinition>("Assets/Data/Generated/CSVImport/Runtime/Flags/hidden_info_detected.asset"),
            VisitorRememberedFlag = LoadRequired<SO_FlagDefinition>("Assets/Data/Generated/CSVImport/Runtime/Flags/visitor_remembered.asset"),

            NemoSpeaker = LoadRequired<SO_DialogueSpeakerDefinition>("Assets/Data/Generated/CSVImport/Week/DialogueSpeakers/speaker_nemo.asset"),
            MaidSpeaker = LoadRequired<SO_DialogueSpeakerDefinition>("Assets/Data/Generated/CSVImport/Week/DialogueSpeakers/speaker_maid.asset"),
            ParentSpeaker = LoadRequired<SO_DialogueSpeakerDefinition>("Assets/Data/Generated/CSVImport/Week/DialogueSpeakers/speaker_parent.asset"),
            TutorSpeaker = LoadRequired<SO_DialogueSpeakerDefinition>("Assets/Data/Generated/CSVImport/Week/DialogueSpeakers/speaker_tutor.asset"),
        };
    }

    private static TestInteractions CreateCommonInteractions(SharedAssets shared)
    {
        const string folder = "Common/Interactions";

        SO_CardInteractionDefinition trustPlus1 = CreateStatDeltaInteraction(folder, "Interaction_TEST_TrustPlus1.asset", "TEST_TrustPlus1", EChildStatusType.Trust, 1);
        SO_CardInteractionDefinition curiosityPlus1 = CreateStatDeltaInteraction(folder, "Interaction_TEST_CuriosityPlus1.asset", "TEST_CuriosityPlus1", EChildStatusType.Curiosity, 1);
        SO_CardInteractionDefinition anxietyPlus1 = CreateStatDeltaInteraction(folder, "Interaction_TEST_AnxietyPlus1.asset", "TEST_AnxietyPlus1", EChildStatusType.Anxiety, 1);
        SO_CardInteractionDefinition obediencePlus1 = CreateStatDeltaInteraction(folder, "Interaction_TEST_ObediencePlus1.asset", "TEST_ObediencePlus1", EChildStatusType.Obedience, 1);

        SO_CardInteractionDefinition setLetterSuspected = CreateSetFlagInteraction(folder, "Interaction_TEST_SetLetterSuspected.asset", "TEST_SetFlag_LetterSuspected", shared.LetterSuspectedFlag);
        SO_CardInteractionDefinition setExternalInterest = CreateSetFlagInteraction(folder, "Interaction_TEST_SetExternalInterest.asset", "TEST_SetFlag_ExternalInterest", shared.ExternalInterestFlag);
        SO_CardInteractionDefinition setHiddenInfoDetected = CreateSetFlagInteraction(folder, "Interaction_TEST_SetHiddenInfoDetected.asset", "TEST_SetFlag_HiddenInfoDetected", shared.HiddenInfoDetectedFlag);
        SO_CardInteractionDefinition setVisitorRemembered = CreateSetFlagInteraction(folder, "Interaction_TEST_SetVisitorRemembered.asset", "TEST_SetFlag_VisitorRemembered", shared.VisitorRememberedFlag);

        SO_CardInteractionDefinition groupCuriosityAndExternal = CreateGroupInteraction(
            folder,
            "Interaction_TEST_Group_CuriosityPlus1_ExternalInterest.asset",
            "TEST_Group_CuriosityPlus1_And_ExternalInterest",
            curiosityPlus1,
            setExternalInterest);

        SO_CardInteractionDefinition conditionalCuriosity3TrustPlus1 = CreateConditionalInteraction(
            folder,
            "Interaction_TEST_Conditional_Curiosity3ToTrustPlus1.asset",
            "TEST_Conditional_IfCuriosityAtLeast3_ThenTrustPlus1",
            EChildStatusType.Curiosity,
            3,
            EChildStatusType.Trust,
            1);

        return new TestInteractions
        {
            TrustPlus1 = trustPlus1,
            CuriosityPlus1 = curiosityPlus1,
            AnxietyPlus1 = anxietyPlus1,
            ObediencePlus1 = obediencePlus1,
            SetLetterSuspected = setLetterSuspected,
            SetExternalInterest = setExternalInterest,
            SetHiddenInfoDetected = setHiddenInfoDetected,
            SetVisitorRemembered = setVisitorRemembered,
            GroupCuriosityPlus1AndExternalInterest = groupCuriosityAndExternal,
            ConditionalIfCuriosity3ThenTrustPlus1 = conditionalCuriosity3TrustPlus1,

            LogW1WeekStart = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_WeekStart.asset", "TEST_Log_W1_WeekStart", "[W1] WeekStart interaction executed."),
            LogW1WeekEnd = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_WeekEnd.asset", "TEST_Log_W1_WeekEnd", "[W1] WeekEnd interaction executed."),
            LogW1Routine = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_Routine.asset", "TEST_Log_W1_Routine", "[W1] Routine step OnEnter executed."),
            LogW1Story = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_Story.asset", "TEST_Log_W1_Story", "[W1] Story step OnEnter executed."),
            LogW1ChoiceA = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_ChoiceA.asset", "TEST_Log_W1_ChoiceA", "[W1] Choice A result applied."),
            LogW1ChoiceB = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W1_ChoiceB.asset", "TEST_Log_W1_ChoiceB", "[W1] Choice B result applied."),

            LogW2Routine = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W2_Routine.asset", "TEST_Log_W2_Routine", "[W2] Routine event triggered by textbook direct semantic."),
            LogW2Story = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W2_Story.asset", "TEST_Log_W2_Story", "[W2] Story event passed information semantic condition."),
            LogW2Night = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W2_Night.asset", "TEST_Log_W2_Night", "[W2] Night dialogue passed information type count condition."),

            LogW3WeekStart = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W3_WeekStart.asset", "TEST_Log_W3_WeekStart", "[W3] WeekStart group interaction executed."),
            LogW3Routine = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W3_Routine.asset", "TEST_Log_W3_Routine", "[W3] Routine event triggered by visitor direct semantic."),
            LogW3Step = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W3_Step.asset", "TEST_Log_W3_Step", "[W3] Conditional OnEnter executed."),
            LogW3Complete = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W3_Complete.asset", "TEST_Log_W3_Complete", "[W3] Event complete interactions executed."),
            LogW3Night = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W3_Night.asset", "TEST_Log_W3_Night", "[W3] Night dialogue unlocked by HiddenInfoDetected flag."),

            LogW4Step1 = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W4_Step1.asset", "TEST_Log_W4_Step1", "[W4] Multi-step event Step1 OnEnter executed."),
            LogW4Step3 = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W4_Step3.asset", "TEST_Log_W4_Step3", "[W4] Multi-step event Step3 reached from Choice A."),
            LogW4ChoiceA = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W4_ChoiceA.asset", "TEST_Log_W4_ChoiceA", "[W4] Choice A selected."),
            LogW4ChoiceB = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W4_ChoiceB.asset", "TEST_Log_W4_ChoiceB", "[W4] Choice B selected."),
            LogW4FallbackNight = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W4_FallbackNight.asset", "TEST_Log_W4_FallbackNight", "[W4] Fallback night dialogue executed because the higher priority one was blocked."),

            LogW5Routine = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W5_Routine.asset", "TEST_Log_W5_Routine", "[W5] Final week routine triggered."),
            LogW5Story = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W5_Story.asset", "TEST_Log_W5_Story", "[W5] Final week story triggered."),
            LogW5Night = CreateReactionLogInteraction(folder, "Interaction_TEST_Log_W5_Night.asset", "TEST_Log_W5_Night", "[W5] Final week night dialogue triggered."),
        };
    }

    private static SO_WeekDefinition CreateWeek1(SharedAssets shared, TestInteractions interactions)
    {
        const string folder = "Week/week_test_01";

        SO_CardInfoDefinition cardLetter = CreateCard(
            folder,
            "Card_TEST_W1_Letter.asset",
            "[W1][CARD] Default=Blocked -> ROUTINE + STORY trigger",
            shared.LetterType,
            "기본 선택 그대로 실행하면 Letter=Blocked가 적용되어 W1 루틴 이벤트와 스토리 이벤트가 둘 다 열립니다.",
            CreateOption(
                ECardOptionSemantic.Blocked,
                "[Default] Blocked -> trigger W1 routine/story",
                "W1 TEST RESULT: Blocked semantic applied.",
                interactions.AnxietyPlus1,
                interactions.SetLetterSuspected),
            CreateOption(
                ECardOptionSemantic.Direct,
                "Direct -> compare no routine/story flag",
                "W1 TEST RESULT: Direct semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> alternate semantic",
                "W1 TEST RESULT: Modified semantic applied.",
                interactions.CuriosityPlus1));

        SO_CardInfoDefinition cardExternal = CreateCard(
            folder,
            "Card_TEST_W1_External.asset",
            "[W1][CARD] Default=Direct -> NIGHT dialogue trigger",
            shared.ExternalType,
            "기본 선택 그대로 실행하면 External=Direct가 적용되어 W1 밤 대화 이벤트가 열립니다.",
            CreateOption(
                ECardOptionSemantic.Direct,
                "[Default] Direct -> trigger W1 night dialogue",
                "W1 TEST RESULT: External direct semantic applied.",
                interactions.CuriosityPlus1,
                interactions.SetExternalInterest),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> compare no night flag",
                "W1 TEST RESULT: External modified semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked -> compare no night flag",
                "W1 TEST RESULT: External blocked semantic applied.",
                interactions.ObediencePlus1));

        SO_InteractiveEventStepDefinition routineStep = CreateStep(
            folder,
            "Step_TEST_W1_Routine.asset",
            "[W1][ROUTINE] Triggered because Letter=Blocked",
            "테스트 확인 포인트: DayRoutineEvent + related type + preferred semantic.",
            false,
            ENemoVisualState.Neutral,
            CreateLines(
                (shared.NemoSpeaker, "[W1][ROUTINE] Letter card was Blocked, so this routine event fired.")),
            new[] { interactions.LogW1Routine },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition storyStep = CreateStep(
            folder,
            "Step_TEST_W1_Story.asset",
            "[W1][STORY] Triggered because LetterSuspected flag exists",
            "테스트 확인 포인트: StoryEvent + required flag condition.",
            false,
            ENemoVisualState.Neutral,
            CreateLines(
                (shared.ParentSpeaker, "[W1][STORY] Required flag LetterSuspected was found."),
                (shared.NemoSpeaker, "[W1][STORY] Story event is now active.")),
            new[] { interactions.LogW1Story },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition nightFollowStep = CreateStep(
            folder,
            "Step_TEST_W1_Night_Follow.asset",
            "[W1][NIGHT] Follow-up step reached from Choice A",
            "테스트 확인 포인트: Choice.NextStep 연결.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.NemoSpeaker, "[W1][NIGHT] Choice A moved to the next step successfully.")),
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        InteractiveEventChoiceData choiceA = CreateChoice(
            "[W1][CHOICE A] Show result screen and move to next step",
            CreateLines(
                (shared.NemoSpeaker, "[W1][CHOICE A] Choice result screen opened."),
                (shared.MaidSpeaker, "[W1][CHOICE A] Next step will now load.")),
            "W1 TEST RESULT: Choice A selected.",
            new[] { interactions.TrustPlus1, interactions.SetVisitorRemembered, interactions.LogW1ChoiceA },
            nightFollowStep);

        InteractiveEventChoiceData choiceB = CreateChoice(
            "[W1][CHOICE B] Show result screen and end event",
            CreateLines(
                (shared.MaidSpeaker, "[W1][CHOICE B] Result screen opened and event will end after continue.")),
            "W1 TEST RESULT: Choice B selected.",
            new[] { interactions.AnxietyPlus1, interactions.LogW1ChoiceB },
            null);

        SO_InteractiveEventStepDefinition nightStep = CreateStep(
            folder,
            "Step_TEST_W1_Night.asset",
            "[W1][NIGHT] Triggered because ExternalInterest flag exists",
            "테스트 확인 포인트: PrivateDialogue + choice result screen + next step branching.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.NemoSpeaker, "[W1][NIGHT] ExternalInterest flag unlocked this night dialogue."),
                (shared.MaidSpeaker, "[W1][NIGHT] Pick Choice A or Choice B to test result flow.")),
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { choiceA, choiceB },
            null);

        SO_DayRoutineEventDefinition routineEvent = CreateRoutineEvent(
            folder,
            "Event_TEST_W1_Routine.asset",
            "test_w1_routine_letter_blocked",
            "[W1] RoutineEvent LetterBlocked",
            100,
            routineStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>(),
            new[] { shared.LetterType },
            new[] { ECardOptionSemantic.Blocked });

        SO_StoryEventDefinition storyEvent = CreateStoryEvent(
            folder,
            "Event_TEST_W1_Story.asset",
            "test_w1_story_flag_required",
            "[W1] StoryEvent RequiredFlag",
            90,
            storyStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { shared.LetterSuspectedFlag },
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        SO_PrivateDialogueDefinition nightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W1_Night.asset",
            "test_w1_night_external_interest",
            "[W1] NightDialogue ExternalInterest",
            80,
            nightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { shared.ExternalInterestFlag },
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        return CreateWeekDefinition(
            folder,
            "WeekDefinition_TEST_W1.asset",
            "test_week_01",
            1,
            "[TEST WEEK 1] Semantic + RequiredFlag + ChoiceResult",
            "기본 선택 그대로 실행하면 Routine, Story, Night가 모두 열립니다. 추천 검증: 카드 선택 후 밤 대화에서 Choice A/B 둘 다 비교.",
            new[] { interactions.LogW1WeekStart },
            new[] { interactions.LogW1WeekEnd },
            new[] { cardLetter, cardExternal },
            new[] { routineEvent },
            new[] { storyEvent },
            new[] { nightEvent });
    }

    private static SO_WeekDefinition CreateWeek2(SharedAssets shared, TestInteractions interactions)
    {
        const string folder = "Week/week_test_02";

        SO_CardInfoDefinition cardTextbook = CreateCard(
            folder,
            "Card_TEST_W2_Textbook.asset",
            "[W2][CARD] Default=Direct -> satisfy info semantic condition",
            shared.TextbookType,
            "기본 선택 그대로 실행하면 Textbook=Direct가 적용되어 정보 타입 + semantic 조건을 만족합니다.",
            CreateOption(
                ECardOptionSemantic.Direct,
                "[Default] Direct -> satisfy story condition",
                "W2 TEST RESULT: Textbook direct semantic applied.",
                interactions.CuriosityPlus1),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> fail semantic filter",
                "W2 TEST RESULT: Textbook modified semantic applied.",
                interactions.ObediencePlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked -> fail semantic filter",
                "W2 TEST RESULT: Textbook blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_CardInfoDefinition cardHouseTalk = CreateCard(
            folder,
            "Card_TEST_W2_HouseTalk.asset",
            "[W2][CARD] Default=Modified -> still satisfy info type count",
            shared.HouseTalkType,
            "이 카드는 semantic과 무관하게 HouseTalk 타입 수량 조건만 검사합니다.",
            CreateOption(
                ECardOptionSemantic.Modified,
                "[Default] Modified -> still counts for type condition",
                "W2 TEST RESULT: HouseTalk modified semantic applied.",
                interactions.ObediencePlus1),
            CreateOption(
                ECardOptionSemantic.Direct,
                "Direct -> same type condition",
                "W2 TEST RESULT: HouseTalk direct semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked -> same type condition",
                "W2 TEST RESULT: HouseTalk blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_InteractiveEventStepDefinition routineStep = CreateStep(
            folder,
            "Step_TEST_W2_Routine.asset",
            "[W2][ROUTINE] Triggered because Textbook=Direct",
            "테스트 확인 포인트: DayRoutineEvent semantic direct 매칭.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.TutorSpeaker, "[W2][ROUTINE] Textbook direct semantic matched as expected.")),
            new[] { interactions.LogW2Routine },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition storyStep = CreateStep(
            folder,
            "Step_TEST_W2_Story.asset",
            "[W2][STORY] Triggered by InformationType + Semantic filter",
            "테스트 확인 포인트: Information requirement with semantic filter.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.TutorSpeaker, "[W2][STORY] Textbook direct count >= 1 check passed."),
                (shared.NemoSpeaker, "[W2][STORY] Information semantic filter works.")),
            new[] { interactions.LogW2Story },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition nightStep = CreateStep(
            folder,
            "Step_TEST_W2_Night.asset",
            "[W2][NIGHT] Triggered by InformationType count only",
            "테스트 확인 포인트: Information requirement without semantic filter.",
            false,
            ENemoVisualState.Neutral,
            CreateLines(
                (shared.MaidSpeaker, "[W2][NIGHT] HouseTalk count >= 1 check passed without semantic filter.")),
            new[] { interactions.LogW2Night },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_DayRoutineEventDefinition routineEvent = CreateRoutineEvent(
            folder,
            "Event_TEST_W2_Routine.asset",
            "test_w2_routine_textbook_direct",
            "[W2] RoutineEvent TextbookDirect",
            100,
            routineStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>(),
            new[] { shared.TextbookType },
            new[] { ECardOptionSemantic.Direct });

        SO_StoryEventDefinition storyEvent = CreateStoryEvent(
            folder,
            "Event_TEST_W2_Story.asset",
            "test_w2_story_info_semantic",
            "[W2] StoryEvent InformationSemantic",
            90,
            storyStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            new[]
            {
                CreateInfoRequirement(shared.TextbookType, true, ECardOptionSemantic.Direct, 1),
            });

        SO_PrivateDialogueDefinition nightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W2_Night.asset",
            "test_w2_night_info_count",
            "[W2] NightDialogue InformationCount",
            80,
            nightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            new[]
            {
                CreateInfoRequirement(shared.HouseTalkType, false, default, 1),
            });

        return CreateWeekDefinition(
            folder,
            "WeekDefinition_TEST_W2.asset",
            "test_week_02",
            2,
            "[TEST WEEK 2] InformationType + SemanticCondition",
            "기본 선택 그대로 실행하면 정보 조건 기반 Story/Night 이벤트가 모두 열립니다. 추천 검증: Textbook semantic을 바꿔서 Story만 꺼지는지 비교.",
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { cardTextbook, cardHouseTalk },
            new[] { routineEvent },
            new[] { storyEvent },
            new[] { nightEvent });
    }

    private static SO_WeekDefinition CreateWeek3(SharedAssets shared, TestInteractions interactions)
    {
        const string folder = "Week/week_test_03";

        SO_CardInfoDefinition cardVisitor = CreateCard(
            folder,
            "Card_TEST_W3_Visitor.asset",
            "[W3][CARD] Default=Direct -> visitor routine compare",
            shared.VisitorType,
            "이 주차는 WeekStart group interaction으로 Curiosity가 먼저 올라갑니다. 기본 선택으로 visitor direct 루틴도 함께 확인할 수 있습니다.",
            CreateOption(
                ECardOptionSemantic.Direct,
                "[Default] Direct -> visitor routine compare",
                "W3 TEST RESULT: Visitor direct semantic applied.",
                interactions.CuriosityPlus1,
                interactions.SetVisitorRemembered),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> alternate semantic",
                "W3 TEST RESULT: Visitor modified semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked -> raise anxiety and test stat max fail",
                "W3 TEST RESULT: Visitor blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_CardInfoDefinition cardLetter = CreateCard(
            folder,
            "Card_TEST_W3_Letter.asset",
            "[W3][CARD] Default=Direct -> extra trust before conditional",
            shared.LetterType,
            "이 카드는 통계 변화 비교용입니다.",
            CreateOption(
                ECardOptionSemantic.Direct,
                "[Default] Direct -> extra trust",
                "W3 TEST RESULT: Letter direct semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> curiosity compare",
                "W3 TEST RESULT: Letter modified semantic applied.",
                interactions.CuriosityPlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked -> anxiety compare",
                "W3 TEST RESULT: Letter blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_InteractiveEventStepDefinition routineStep = CreateStep(
            folder,
            "Step_TEST_W3_Routine.asset",
            "[W3][ROUTINE] Triggered because Visitor=Direct",
            "테스트 확인 포인트: RoutineEvent visitor direct 매칭.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.ParentSpeaker, "[W3][ROUTINE] Visitor direct semantic matched.")),
            new[] { interactions.LogW3Routine },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition storyStep = CreateStep(
            folder,
            "Step_TEST_W3_Story.asset",
            "[W3][STORY] Triggered because Curiosity>=3 and Anxiety<=3",
            "테스트 확인 포인트: Stat 조건 + Conditional OnEnter + EventComplete interaction.",
            false,
            ENemoVisualState.Curious,
            CreateLines(
                (shared.NemoSpeaker, "[W3][STORY] Stat condition passed."),
                (shared.TutorSpeaker, "[W3][STORY] Conditional interaction should also run on enter.")),
            new[] { interactions.ConditionalIfCuriosity3ThenTrustPlus1, interactions.LogW3Step },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition nightStep = CreateStep(
            folder,
            "Step_TEST_W3_Night.asset",
            "[W3][NIGHT] Triggered because HiddenInfoDetected flag exists",
            "테스트 확인 포인트: EventComplete interaction -> required flag chain.",
            false,
            ENemoVisualState.Conflicted,
            CreateLines(
                (shared.NemoSpeaker, "[W3][NIGHT] HiddenInfoDetected flag was created by EventComplete interaction.")),
            new[] { interactions.LogW3Night },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_DayRoutineEventDefinition routineEvent = CreateRoutineEvent(
            folder,
            "Event_TEST_W3_Routine.asset",
            "test_w3_routine_visitor_direct",
            "[W3] RoutineEvent VisitorDirect",
            100,
            routineStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>(),
            new[] { shared.VisitorType },
            new[] { ECardOptionSemantic.Direct });

        SO_StoryEventDefinition storyEvent = CreateStoryEvent(
            folder,
            "Event_TEST_W3_Story.asset",
            "test_w3_story_stat_condition",
            "[W3] StoryEvent StatCondition",
            95,
            storyStep,
            new[] { interactions.SetHiddenInfoDetected, interactions.LogW3Complete },
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            new[]
            {
                CreateStatRequirement(EChildStatusType.Curiosity, true, 3, true, 5),
                CreateStatRequirement(EChildStatusType.Anxiety, false, 0, true, 3),
            },
            Array.Empty<InformationTypeConditionData>());

        SO_PrivateDialogueDefinition nightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W3_Night.asset",
            "test_w3_night_hidden_flag",
            "[W3] NightDialogue HiddenInfoDetected",
            80,
            nightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { shared.HiddenInfoDetectedFlag },
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        return CreateWeekDefinition(
            folder,
            "WeekDefinition_TEST_W3.asset",
            "test_week_03",
            3,
            "[TEST WEEK 3] WeekStartGroup + StatCondition + EventComplete",
            "기본 선택 그대로 실행하면 WeekStart group interaction으로 Curiosity가 먼저 올라가고, 그 덕분에 StatCondition Story가 열립니다.",
            new[] { interactions.GroupCuriosityPlus1AndExternalInterest, interactions.LogW3WeekStart },
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { cardVisitor, cardLetter },
            new[] { routineEvent },
            new[] { storyEvent },
            new[] { nightEvent });
    }

    private static SO_WeekDefinition CreateWeek4(SharedAssets shared, TestInteractions interactions)
    {
        const string folder = "Week/week_test_04";

        SO_CardInfoDefinition cardHouseTalk = CreateCard(
            folder,
            "Card_TEST_W4_HouseTalk.asset",
            "[W4][CARD] Default=Direct -> multi-step compare card",
            shared.HouseTalkType,
            "이 카드는 주차 진행 비교용 카드입니다.",
            CreateOption(
                ECardOptionSemantic.Direct,
                "[Default] Direct",
                "W4 TEST RESULT: HouseTalk direct semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified",
                "W4 TEST RESULT: HouseTalk modified semantic applied.",
                interactions.ObediencePlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked",
                "W4 TEST RESULT: HouseTalk blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_CardInfoDefinition cardExternal = CreateCard(
            folder,
            "Card_TEST_W4_External.asset",
            "[W4][CARD] Default=Modified -> alternate card compare",
            shared.ExternalType,
            "이 카드는 선택 그룹/상태 변화 확인용 보조 카드입니다.",
            CreateOption(
                ECardOptionSemantic.Modified,
                "[Default] Modified",
                "W4 TEST RESULT: External modified semantic applied.",
                interactions.ObediencePlus1),
            CreateOption(
                ECardOptionSemantic.Direct,
                "Direct",
                "W4 TEST RESULT: External direct semantic applied.",
                interactions.CuriosityPlus1),
            CreateOption(
                ECardOptionSemantic.Blocked,
                "Blocked",
                "W4 TEST RESULT: External blocked semantic applied.",
                interactions.AnxietyPlus1));

        SO_InteractiveEventStepDefinition step3 = CreateStep(
            folder,
            "Step_TEST_W4_Step3.asset",
            "[W4][STORY] Step3 reached from Choice A",
            "테스트 확인 포인트: Choice.NextStep으로만 도달하는 마지막 step.",
            false,
            ENemoVisualState.Trusting,
            CreateLines(
                (shared.NemoSpeaker, "[W4][STORY] Step3 loaded only because Choice A was selected.")),
            new[] { interactions.LogW4Step3 },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        InteractiveEventChoiceData choiceA = CreateChoice(
            "[W4][CHOICE A] Result + move to Step3",
            CreateLines(
                (shared.NemoSpeaker, "[W4][CHOICE A] Step3 will open next.")),
            "W4 TEST RESULT: Choice A selected.",
            new[] { interactions.ObediencePlus1, interactions.LogW4ChoiceA },
            step3);

        InteractiveEventChoiceData choiceB = CreateChoice(
            "[W4][CHOICE B] Result + end event",
            CreateLines(
                (shared.NemoSpeaker, "[W4][CHOICE B] Event will end after this result screen.")),
            "W4 TEST RESULT: Choice B selected.",
            new[] { interactions.AnxietyPlus1, interactions.LogW4ChoiceB },
            null);

        SO_InteractiveEventStepDefinition step2 = CreateStep(
            folder,
            "Step_TEST_W4_Step2.asset",
            "[W4][STORY] Step2 has choices and custom visual state",
            "테스트 확인 포인트: DefaultNextStep 이후 Choice 분기 + custom visual state.",
            true,
            ENemoVisualState.Conflicted,
            CreateLines(
                (shared.NemoSpeaker, "[W4][STORY] You are now on Step2. Pick A or B.")),
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { choiceA, choiceB },
            null);

        SO_InteractiveEventStepDefinition step1 = CreateStep(
            folder,
            "Step_TEST_W4_Step1.asset",
            "[W4][STORY] Step1 auto-continues to Step2",
            "테스트 확인 포인트: Step.DefaultNextStep.",
            false,
            ENemoVisualState.Neutral,
            CreateLines(
                (shared.MaidSpeaker, "[W4][STORY] Continue once and Step2 should open.")),
            new[] { interactions.LogW4Step1 },
            Array.Empty<InteractiveEventChoiceData>(),
            step2);

        SO_InteractiveEventStepDefinition fallbackNightStep = CreateStep(
            folder,
            "Step_TEST_W4_NightFallback.asset",
            "[W4][NIGHT] Fallback dialogue",
            "테스트 확인 포인트: blocked flag로 높은 우선순위 dialogue가 빠지고 fallback만 남는지 확인.",
            false,
            ENemoVisualState.Neutral,
            CreateLines(
                (shared.MaidSpeaker, "[W4][NIGHT] This fallback dialogue appeared because the higher priority one was blocked.")),
            new[] { interactions.LogW4FallbackNight },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition blockedNightStep = CreateStep(
            folder,
            "Step_TEST_W4_NightBlocked.asset",
            "[W4][NIGHT] SHOULD NOT APPEAR",
            "이 step이 보이면 blocked flag 검증이 실패한 것입니다.",
            false,
            ENemoVisualState.Anxious,
            CreateLines(
                (shared.NemoSpeaker, "[W4][NIGHT] This line should stay hidden because HiddenInfoDetected blocks it.")),
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_StoryEventDefinition storyEvent = CreateStoryEvent(
            folder,
            "Event_TEST_W4_Story.asset",
            "test_w4_story_multistep",
            "[W4] StoryEvent MultiStep",
            100,
            step1,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        SO_PrivateDialogueDefinition blockedNightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W4_NightBlocked.asset",
            "test_w4_night_blocked",
            "[W4] NightDialogue SHOULD_BE_BLOCKED",
            200,
            blockedNightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            new[] { shared.HiddenInfoDetectedFlag },
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        SO_PrivateDialogueDefinition fallbackNightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W4_NightFallback.asset",
            "test_w4_night_fallback",
            "[W4] NightDialogue Fallback",
            100,
            fallbackNightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        return CreateWeekDefinition(
            folder,
            "WeekDefinition_TEST_W4.asset",
            "test_week_04",
            4,
            "[TEST WEEK 4] MultiStep + ChoiceBranch + BlockedFallback",
            "기본 선택 그대로 실행하면 Multi-step Story가 열리고, HiddenInfoDetected 때문에 밤 대화는 fallback만 남습니다.",
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { cardHouseTalk, cardExternal },
            Array.Empty<SO_DayRoutineEventDefinition>(),
            new[] { storyEvent },
            new[] { blockedNightEvent, fallbackNightEvent });
    }

    private static SO_WeekDefinition CreateWeek5(SharedAssets shared, TestInteractions interactions)
    {
        const string folder = "Week/week_test_05";

        SO_CardInfoDefinition cardLetter = CreateCard(
            folder,
            "Card_TEST_W5_Letter.asset",
            "[W5][CARD] Default=Blocked -> final anxiety boost #1",
            shared.LetterType,
            "기본 선택 그대로 실행하면 최종 Anxiety가 올라가서 엔딩 분기 비교가 쉬워집니다.",
            CreateOption(
                ECardOptionSemantic.Blocked,
                "[Default] Blocked -> increase anxiety",
                "W5 TEST RESULT: Final letter blocked semantic applied.",
                interactions.AnxietyPlus1,
                interactions.SetLetterSuspected),
            CreateOption(
                ECardOptionSemantic.Direct,
                "Direct -> reduce ending anxiety pressure",
                "W5 TEST RESULT: Final letter direct semantic applied.",
                interactions.TrustPlus1),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> curiosity compare",
                "W5 TEST RESULT: Final letter modified semantic applied.",
                interactions.CuriosityPlus1));

        SO_CardInfoDefinition cardExternal = CreateCard(
            folder,
            "Card_TEST_W5_External.asset",
            "[W5][CARD] Default=Blocked -> final anxiety boost #2",
            shared.ExternalType,
            "기본 선택 그대로 실행하면 Anxiety가 한 번 더 올라가 기본 테스트 루트에서 anxious ending이 잘 보이도록 구성했습니다.",
            CreateOption(
                ECardOptionSemantic.Blocked,
                "[Default] Blocked -> increase anxiety again",
                "W5 TEST RESULT: Final external blocked semantic applied.",
                interactions.AnxietyPlus1),
            CreateOption(
                ECardOptionSemantic.Direct,
                "Direct -> curiosity compare",
                "W5 TEST RESULT: Final external direct semantic applied.",
                interactions.CuriosityPlus1,
                interactions.SetExternalInterest),
            CreateOption(
                ECardOptionSemantic.Modified,
                "Modified -> obedience compare",
                "W5 TEST RESULT: Final external modified semantic applied.",
                interactions.ObediencePlus1));

        SO_InteractiveEventStepDefinition routineStep = CreateStep(
            folder,
            "Step_TEST_W5_Routine.asset",
            "[W5][ROUTINE] Final routine",
            "테스트 확인 포인트: 마지막 주차에서도 동일한 event 파이프라인이 정상 동작하는지 확인.",
            false,
            ENemoVisualState.Anxious,
            CreateLines(
                (shared.NemoSpeaker, "[W5][ROUTINE] Final routine event triggered.")),
            new[] { interactions.LogW5Routine },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition storyStep = CreateStep(
            folder,
            "Step_TEST_W5_Story.asset",
            "[W5][STORY] Final story before ending",
            "테스트 확인 포인트: 마지막 주차 스토리 실행 후 엔딩으로 자연스럽게 이어지는지 확인.",
            true,
            ENemoVisualState.Anxious,
            CreateLines(
                (shared.ParentSpeaker, "[W5][STORY] Final story event triggered before ending.")),
            new[] { interactions.LogW5Story },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_InteractiveEventStepDefinition nightStep = CreateStep(
            folder,
            "Step_TEST_W5_Night.asset",
            "[W5][NIGHT] Final night dialogue before ending",
            "테스트 확인 포인트: 마지막 night dialogue 종료 후 Ending screen 진입.",
            false,
            ENemoVisualState.Anxious,
            CreateLines(
                (shared.NemoSpeaker, "[W5][NIGHT] After this event finishes, the ending screen should appear.")),
            new[] { interactions.LogW5Night },
            Array.Empty<InteractiveEventChoiceData>(),
            null);

        SO_DayRoutineEventDefinition routineEvent = CreateRoutineEvent(
            folder,
            "Event_TEST_W5_Routine.asset",
            "test_w5_routine_letter_blocked",
            "[W5] RoutineEvent FinalLetterBlocked",
            100,
            routineStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>(),
            new[] { shared.LetterType },
            new[] { ECardOptionSemantic.Blocked });

        SO_StoryEventDefinition storyEvent = CreateStoryEvent(
            folder,
            "Event_TEST_W5_Story.asset",
            "test_w5_story_external_flag",
            "[W5] StoryEvent FinalFlagCheck",
            90,
            storyStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { shared.ExternalInterestFlag },
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        SO_PrivateDialogueDefinition nightEvent = CreatePrivateDialogue(
            folder,
            "Event_TEST_W5_Night.asset",
            "test_w5_night_final",
            "[W5] NightDialogue Final",
            80,
            nightStep,
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<SO_FlagDefinition>(),
            Array.Empty<WeekStatRequirementData>(),
            Array.Empty<InformationTypeConditionData>());

        return CreateWeekDefinition(
            folder,
            "WeekDefinition_TEST_W5.asset",
            "test_week_05",
            5,
            "[TEST WEEK 5] Final Week + Ending",
            "기본 선택 그대로 실행하면 Anxiety가 올라가 마지막 엔딩 비교가 쉬워집니다. 이 주차 종료 후 엔딩 화면이 바로 나와야 합니다.",
            Array.Empty<SO_CardInteractionDefinition>(),
            Array.Empty<SO_CardInteractionDefinition>(),
            new[] { cardLetter, cardExternal },
            new[] { routineEvent },
            new[] { storyEvent },
            new[] { nightEvent });
    }

    private static SO_WeekDefinition CreateWeekDefinition(
        string relativeFolder,
        string fileName,
        string id,
        int weekIndex,
        string title,
        string summary,
        SO_CardInteractionDefinition[] onWeekStartInteractions,
        SO_CardInteractionDefinition[] onWeekEndInteractions,
        SO_CardInfoDefinition[] cards,
        SO_DayRoutineEventDefinition[] routineEvents,
        SO_StoryEventDefinition[] storyEvents,
        SO_PrivateDialogueDefinition[] nightEvents)
    {
        SO_WeekPreTurnDefinition preTurn = CreateAsset<SO_WeekPreTurnDefinition>(relativeFolder, $"WeekPreTurn_{fileName}", $"{title}_PreTurn");
        SetField(preTurn, "_title", $"{title} / PreTurn");
        SetField(preTurn, "_summary", summary);
        SetField(preTurn, "_informationCards", BuildWeekCardEntries(cards));

        SO_WeekDayFlowDefinition dayFlow = CreateAsset<SO_WeekDayFlowDefinition>(relativeFolder, $"WeekDayFlow_{fileName}", $"{title}_DayFlow");
        SetField(dayFlow, "_routineEvents", routineEvents ?? Array.Empty<SO_DayRoutineEventDefinition>());
        SetField(dayFlow, "_storyEvents", storyEvents ?? Array.Empty<SO_StoryEventDefinition>());

        SO_WeekNightFlowDefinition nightFlow = CreateAsset<SO_WeekNightFlowDefinition>(relativeFolder, $"WeekNightFlow_{fileName}", $"{title}_NightFlow");
        SetField(nightFlow, "_dialogues", nightEvents ?? Array.Empty<SO_PrivateDialogueDefinition>());

        SO_WeekDefinition week = CreateAsset<SO_WeekDefinition>(relativeFolder, fileName, title);
        SetField(week, "_id", id);
        SetField(week, "_weekIndex", weekIndex);
        SetField(week, "_title", title);
        SetField(week, "_summary", summary);
        SetField(week, "_preTurn", preTurn);
        SetField(week, "_dayFlow", dayFlow);
        SetField(week, "_nightFlow", nightFlow);
        SetField(week, "_weekRules", Array.Empty<SO_WeekRuleDefinition>());
        SetField(week, "_onWeekStartInteractions", onWeekStartInteractions ?? Array.Empty<SO_CardInteractionDefinition>());
        SetField(week, "_onWeekEndInteractions", onWeekEndInteractions ?? Array.Empty<SO_CardInteractionDefinition>());
        SetField(week, "_cinematicProfile", null);

        EditorUtility.SetDirty(preTurn);
        EditorUtility.SetDirty(dayFlow);
        EditorUtility.SetDirty(nightFlow);
        EditorUtility.SetDirty(week);
        return week;
    }

    private static SO_DayRoutineEventDefinition CreateRoutineEvent(
        string relativeFolder,
        string fileName,
        string id,
        string title,
        int priority,
        SO_InteractiveEventStepDefinition firstStep,
        SO_CardInteractionDefinition[] onCompletedInteractions,
        SO_FlagDefinition[] requiredFlags,
        SO_FlagDefinition[] blockedFlags,
        WeekStatRequirementData[] statRequirements,
        InformationTypeConditionData[] infoRequirements,
        SO_CardInfoTypeDefinition[] relatedTypes,
        ECardOptionSemantic[] preferredSemantics)
    {
        SO_DayRoutineEventDefinition asset = CreateAsset<SO_DayRoutineEventDefinition>(relativeFolder, fileName, title);
        ConfigureInteractiveEvent(asset, id, title, priority, firstStep, onCompletedInteractions, requiredFlags, blockedFlags, statRequirements, infoRequirements);
        SetField(asset, "_relatedInformationTypes", relatedTypes ?? Array.Empty<SO_CardInfoTypeDefinition>());
        SetField(asset, "_preferredSemantics", preferredSemantics ?? Array.Empty<ECardOptionSemantic>());
        EditorUtility.SetDirty(asset);
        return asset;
    }

    private static SO_StoryEventDefinition CreateStoryEvent(
        string relativeFolder,
        string fileName,
        string id,
        string title,
        int priority,
        SO_InteractiveEventStepDefinition firstStep,
        SO_CardInteractionDefinition[] onCompletedInteractions,
        SO_FlagDefinition[] requiredFlags,
        SO_FlagDefinition[] blockedFlags,
        WeekStatRequirementData[] statRequirements,
        InformationTypeConditionData[] infoRequirements)
    {
        SO_StoryEventDefinition asset = CreateAsset<SO_StoryEventDefinition>(relativeFolder, fileName, title);
        ConfigureInteractiveEvent(asset, id, title, priority, firstStep, onCompletedInteractions, requiredFlags, blockedFlags, statRequirements, infoRequirements);
        EditorUtility.SetDirty(asset);
        return asset;
    }

    private static SO_PrivateDialogueDefinition CreatePrivateDialogue(
        string relativeFolder,
        string fileName,
        string id,
        string title,
        int priority,
        SO_InteractiveEventStepDefinition firstStep,
        SO_CardInteractionDefinition[] onCompletedInteractions,
        SO_FlagDefinition[] requiredFlags,
        SO_FlagDefinition[] blockedFlags,
        WeekStatRequirementData[] statRequirements,
        InformationTypeConditionData[] infoRequirements)
    {
        SO_PrivateDialogueDefinition asset = CreateAsset<SO_PrivateDialogueDefinition>(relativeFolder, fileName, title);
        ConfigureInteractiveEvent(asset, id, title, priority, firstStep, onCompletedInteractions, requiredFlags, blockedFlags, statRequirements, infoRequirements);
        EditorUtility.SetDirty(asset);
        return asset;
    }

    private static void ConfigureInteractiveEvent(
        SO_InteractiveEventDefinition asset,
        string id,
        string title,
        int priority,
        SO_InteractiveEventStepDefinition firstStep,
        SO_CardInteractionDefinition[] onCompletedInteractions,
        SO_FlagDefinition[] requiredFlags,
        SO_FlagDefinition[] blockedFlags,
        WeekStatRequirementData[] statRequirements,
        InformationTypeConditionData[] infoRequirements)
    {
        SetField(asset, "_id", id);
        SetField(asset, "_title", title);
        SetField(asset, "_priority", priority);
        SetField(asset, "_firstStep", firstStep);
        SetField(asset, "_onCompletedInteractions", onCompletedInteractions ?? Array.Empty<SO_CardInteractionDefinition>());
        SetField(asset, "_cinematicProfile", null);

        WeekEventConditionData conditions = new();
        SetField(conditions, "_requiredFlags", requiredFlags ?? Array.Empty<SO_FlagDefinition>());
        SetField(conditions, "_blockedFlags", blockedFlags ?? Array.Empty<SO_FlagDefinition>());
        SetField(conditions, "_statRequirements", statRequirements ?? Array.Empty<WeekStatRequirementData>());
        SetField(conditions, "_informationRequirements", infoRequirements ?? Array.Empty<InformationTypeConditionData>());
        SetField(asset, "_conditions", conditions);
    }

    private static SO_InteractiveEventStepDefinition CreateStep(
        string relativeFolder,
        string fileName,
        string title,
        string bodyText,
        bool useCustomVisualState,
        ENemoVisualState visualState,
        DialogueLineData[] dialogueLines,
        SO_CardInteractionDefinition[] onEnterInteractions,
        InteractiveEventChoiceData[] choices,
        SO_InteractiveEventStepDefinition nextStep)
    {
        SO_InteractiveEventStepDefinition step = CreateAsset<SO_InteractiveEventStepDefinition>(relativeFolder, fileName, title);
        SetField(step, "_titleOverride", title);
        SetField(step, "_bodyText", bodyText);
        SetField(step, "_dialogueLines", dialogueLines ?? Array.Empty<DialogueLineData>());
        SetField(step, "_nemoLine", dialogueLines != null && dialogueLines.Length > 0 ? dialogueLines[0].Text : string.Empty);
        SetField(step, "_useCustomVisualState", useCustomVisualState);
        SetField(step, "_visualState", visualState);
        SetField(step, "_onEnterInteractions", onEnterInteractions ?? Array.Empty<SO_CardInteractionDefinition>());
        SetField(step, "_choices", choices ?? Array.Empty<InteractiveEventChoiceData>());
        SetField(step, "_nextStep", nextStep);
        SetField(step, "_cinematicCues", new WeekFlowScreenCues());
        EditorUtility.SetDirty(step);
        return step;
    }

    private static InteractiveEventChoiceData CreateChoice(
        string label,
        DialogueLineData[] responseLines,
        string responseLine,
        SO_CardInteractionDefinition[] interactions,
        SO_InteractiveEventStepDefinition nextStep)
    {
        InteractiveEventChoiceData choice = new();
        SetField(choice, "_label", label);
        SetField(choice, "_responseDialogueLines", responseLines ?? Array.Empty<DialogueLineData>());
        SetField(choice, "_responseLine", responseLine);
        SetField(choice, "_interactions", interactions ?? Array.Empty<SO_CardInteractionDefinition>());
        SetField(choice, "_nextStep", nextStep);
        SetField(choice, "_resultCinematicCues", new WeekFlowScreenCues());
        return choice;
    }

    private static SO_CardInfoDefinition CreateCard(
        string relativeFolder,
        string fileName,
        string title,
        SO_CardInfoTypeDefinition cardType,
        string originalText,
        params CardOptionData[] options)
    {
        SO_CardInfoDefinition card = CreateAsset<SO_CardInfoDefinition>(relativeFolder, fileName, title);
        SetField(card, "_id", Path.GetFileNameWithoutExtension(fileName).ToLowerInvariant());
        SetField(card, "_cardType", cardType);
        SetField(card, "_title", title);
        SetField(card, "_originalText", originalText);
        SetField(card, "_options", options ?? Array.Empty<CardOptionData>());
        EditorUtility.SetDirty(card);
        return card;
    }

    private static CardOptionData CreateOption(
        ECardOptionSemantic semantic,
        string label,
        string presentedText,
        params SO_CardInteractionDefinition[] interactions)
    {
        CardOptionData option = new();
        SetField(option, "_semantic", semantic);
        SetField(option, "_label", label);
        SetField(option, "_presentedText", presentedText);
        SetField(option, "_interactions", interactions ?? Array.Empty<SO_CardInteractionDefinition>());
        return option;
    }

    private static DialogueLineData[] CreateLines(params (SO_DialogueSpeakerDefinition speaker, string text)[] specs)
    {
        if (specs == null || specs.Length == 0)
        {
            return Array.Empty<DialogueLineData>();
        }

        DialogueLineData[] lines = new DialogueLineData[specs.Length];
        for (int i = 0; i < specs.Length; i++)
        {
            DialogueLineData line = new();
            SetField(line, "_speaker", specs[i].speaker);
            SetField(line, "_text", specs[i].text);
            lines[i] = line;
        }

        return lines;
    }

    private static WeekCardEntryData[] BuildWeekCardEntries(IReadOnlyList<SO_CardInfoDefinition> cards)
    {
        if (cards == null || cards.Count == 0)
        {
            return Array.Empty<WeekCardEntryData>();
        }

        WeekCardEntryData[] entries = new WeekCardEntryData[cards.Count];
        for (int i = 0; i < cards.Count; i++)
        {
            WeekCardEntryData entry = new();
            SetField(entry, "_card", cards[i]);
            SetField(entry, "_isRequired", true);
            SetField(entry, "_displayOrder", i);
            entries[i] = entry;
        }

        return entries;
    }

    private static WeekStatRequirementData CreateStatRequirement(
        EChildStatusType statType,
        bool useMinimum,
        int minimumValue,
        bool useMaximum,
        int maximumValue)
    {
        WeekStatRequirementData requirement = new();
        SetField(requirement, "_statType", statType);
        SetField(requirement, "_useMinimum", useMinimum);
        SetField(requirement, "_minimumValue", minimumValue);
        SetField(requirement, "_useMaximum", useMaximum);
        SetField(requirement, "_maximumValue", maximumValue);
        return requirement;
    }

    private static InformationTypeConditionData CreateInfoRequirement(
        SO_CardInfoTypeDefinition informationType,
        bool useSemanticFilter,
        ECardOptionSemantic semantic,
        int minimumCount)
    {
        InformationTypeConditionData requirement = new();
        SetField(requirement, "_informationType", informationType);
        SetField(requirement, "_useSemanticFilter", useSemanticFilter);
        SetField(requirement, "_semantic", semantic);
        SetField(requirement, "_minimumCount", minimumCount);
        return requirement;
    }

    private static SO_CardInteractionDefinition CreateStatDeltaInteraction(
        string relativeFolder,
        string fileName,
        string assetName,
        EChildStatusType statType,
        int amount)
    {
        SO_CardInteraction_StatDelta interaction = CreateAsset<SO_CardInteraction_StatDelta>(relativeFolder, fileName, assetName);
        SetField(interaction, "_statType", statType);
        SetField(interaction, "_amount", amount);
        EditorUtility.SetDirty(interaction);
        return interaction;
    }

    private static SO_CardInteractionDefinition CreateSetFlagInteraction(
        string relativeFolder,
        string fileName,
        string assetName,
        SO_FlagDefinition flag)
    {
        SO_CardInteraction_SetFlag interaction = CreateAsset<SO_CardInteraction_SetFlag>(relativeFolder, fileName, assetName);
        SetField(interaction, "_flagDefinition", flag);
        EditorUtility.SetDirty(interaction);
        return interaction;
    }

    private static SO_CardInteractionDefinition CreateGroupInteraction(
        string relativeFolder,
        string fileName,
        string assetName,
        params SO_CardInteractionDefinition[] interactions)
    {
        SO_CardInteraction_GroupStatDelta interaction = CreateAsset<SO_CardInteraction_GroupStatDelta>(relativeFolder, fileName, assetName);
        SetField(interaction, "_interactions", interactions ?? Array.Empty<SO_CardInteractionDefinition>());
        EditorUtility.SetDirty(interaction);
        return interaction;
    }

    private static SO_CardInteractionDefinition CreateConditionalInteraction(
        string relativeFolder,
        string fileName,
        string assetName,
        EChildStatusType conditionStat,
        int minValue,
        EChildStatusType targetStat,
        int amount)
    {
        SO_CardInteraction_ConditionalStatDelta interaction = CreateAsset<SO_CardInteraction_ConditionalStatDelta>(relativeFolder, fileName, assetName);
        SetField(interaction, "_conditionStat", conditionStat);
        SetField(interaction, "_minValue", minValue);
        SetField(interaction, "_targetStat", targetStat);
        SetField(interaction, "_amount", amount);
        EditorUtility.SetDirty(interaction);
        return interaction;
    }

    private static SO_CardInteractionDefinition CreateReactionLogInteraction(
        string relativeFolder,
        string fileName,
        string assetName,
        string reactionText)
    {
        SO_CardInteraction_AddReactionLog interaction = CreateAsset<SO_CardInteraction_AddReactionLog>(relativeFolder, fileName, assetName);
        SetField(interaction, "_reactionText", reactionText);
        EditorUtility.SetDirty(interaction);
        return interaction;
    }

    private static T CreateAsset<T>(string relativeFolder, string fileName, string assetName)
        where T : ScriptableObject
    {
        string folderPath = $"{OutputRoot}/{relativeFolder}".Replace("\\", "/");
        EnsureFolder(folderPath);

        string assetPath = $"{folderPath}/{fileName}".Replace("\\", "/");
        T asset = ScriptableObject.CreateInstance<T>();
        asset.name = assetName;
        AssetDatabase.CreateAsset(asset, assetPath);
        return asset;
    }

    private static T LoadRequired<T>(string assetPath) where T : UnityEngine.Object
    {
        T asset = AssetDatabase.LoadAssetAtPath<T>(assetPath);
        if (asset == null)
        {
            throw new InvalidOperationException($"Required asset is missing: {assetPath}");
        }

        return asset;
    }

    private static void ResetOutputRoot()
    {
        if (AssetDatabase.IsValidFolder(OutputRoot))
        {
            FileUtil.DeleteFileOrDirectory(OutputRoot);
            FileUtil.DeleteFileOrDirectory($"{OutputRoot}.meta");
        }
    }

    private static void EnsureFolder(string folderPath)
    {
        folderPath = folderPath.Replace("\\", "/");
        string[] parts = folderPath.Split('/');
        if (parts.Length == 0)
        {
            return;
        }

        string current = parts[0];
        for (int i = 1; i < parts.Length; i++)
        {
            string next = $"{current}/{parts[i]}";
            if (!AssetDatabase.IsValidFolder(next))
            {
                AssetDatabase.CreateFolder(current, parts[i]);
            }

            current = next;
        }
    }

    private static void WriteReadme(IReadOnlyList<SO_WeekDefinition> weeks)
    {
        string absolutePath = Path.Combine(Application.dataPath, "Data", "Test", "WeekValidationSamples", "README_WeekValidationSamples.txt");
        string content =
            "5주 검증용 샘플 SO 생성 완료\r\n" +
            "\r\n" +
            "생성 위치: Assets/Data/Test/WeekValidationSamples\r\n" +
            "\r\n" +
            "권장 연결 방식\r\n" +
            "1. WeekFlowController._weekDefinition 에 1주차 asset 연결\r\n" +
            "2. WeekFlowController._weekDefinitions 에 1~5주차 asset 전부 연결\r\n" +
            "\r\n" +
            "기본 선택 안내\r\n" +
            "- 모든 카드는 기본 선택(첫 번째 옵션)만으로도 검증 포인트가 보이게 구성됨\r\n" +
            "- W1: 밤 대화에서 Choice A / B 둘 다 비교 권장\r\n" +
            "- W4: 멀티스텝 스토리에서 Choice A / B 둘 다 비교 권장\r\n" +
            "- W5: 기본 선택 그대로 두면 Anxiety ending 비교가 쉬움\r\n" +
            "\r\n" +
            "주차 목록\r\n";

        foreach (SO_WeekDefinition week in weeks)
        {
            if (week == null)
            {
                continue;
            }

            content += $"- W{week.WeekIndex}: {week.Title}\r\n";
        }

        File.WriteAllText(absolutePath, content);
        AssetDatabase.ImportAsset(OutputRoot);
    }

    private static void SetField(object target, string fieldName, object value)
    {
        Type currentType = target.GetType();
        while (currentType != null)
        {
            FieldInfo field = currentType.GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
            if (field != null)
            {
                field.SetValue(target, value);
                return;
            }

            currentType = currentType.BaseType;
        }

        throw new MissingFieldException(target.GetType().Name, fieldName);
    }
}
